default: &default
  server_port: 3000
  server_host: localhost
  public_url: bar

development:
  <<: *default
  public_url: 'http://localhost:3000'

test:
  <<: *default
  public_url: 'http://test.com'
