development:
  sessions:
    default:
      database: wunderlist
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: wunderlist-test
      hosts:
        - localhost:27017
